#!/usr/bin/env python3
"""
project_templates.py — Plantillas de proyecto multi-lenguaje (v2.7.0).

Crea scaffolds de proyecto completos para:
  - Next.js (React + TypeScript)
  - Go API (chi router + testify)
  - Python CLI (Click + pytest)
  - React Native (mobile)
  - Rust CLI (clap)
  - Java Spring Boot API
  - PHP Laravel API
  - C++ CMake project

Cada plantilla incluye:
  - Estructura de directorios
  - Archivos base (main, config, tests)
  - opencode.json configurado
  - .gitignore
  - README.md

Uso:
  python3 project_templates.py --template nextjs --output /tmp/my-nextjs-app
  python3 project_templates.py --template go-api --output /tmp/my-go-api
  python3 project_templates.py --list
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List

sys.path.insert(0, str(Path(__file__).parent))
from common import log, now_iso, parse_args


TEMPLATES = {
    "nextjs": {
        "description": "Next.js app with TypeScript, Tailwind CSS, Jest, Playwright",
        "languages": ["typescript", "javascript", "css"],
        "files": {
            "package.json": '''{
  "name": "{{name}}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "test": "jest",
    "test:e2e": "playwright test"
  },
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/node": "^22.0.0",
    "@types/react": "^18.0.0",
    "typescript": "^5.5.0",
    "jest": "^29.0.0",
    "@playwright/test": "^1.40.0",
    "tailwindcss": "^3.4.0"
  }
}
''',
            "tsconfig.json": '''{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "bundler",
    "strict": true,
    "jsx": "preserve",
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
''',
            "app/page.tsx": '''export default function Home() {
  return (
    <main>
      <h1>{{name}}</h1>
      <p>Welcome to your Next.js app</p>
    </main>
  );
}
''',
            "app/layout.tsx": '''import "./globals.css";

export const metadata = {
  title: "{{name}}",
  description: "Generated by apolo-dynamic-flow",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
''',
            "app/globals.css": '''@tailwind base;
@tailwind components;
@tailwind utilities;
''',
            ".gitignore": "node_modules/\n.next/\ndist/\n*.log\n.env\n",
            "README.md": "# {{name}}\n\nGenerated by apolo-dynamic-flow v2.7.0\n\n## Getting Started\n\n```bash\nnpm install\nnpm run dev\n```\n",
        }
    },
    "go-api": {
        "description": "Go REST API with chi router, testify, golangci-lint",
        "languages": ["go"],
        "files": {
            "main.go": '''package main

import (
	"log"
	"net/http"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

func main() {
	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`{"status":"ok"}`))
	})

	log.Println("Server starting on :8080")
	log.Fatal(http.ListenAndServe(":8080", r))
}
''',
            "go.mod": '''module {{name}}

go 1.22

require (
	github.com/go-chi/chi/v5 v5.0.0
)
''',
            "main_test.go": '''package main

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestHealthEndpoint(t *testing.T) {
	req := httptest.NewRequest("GET", "/health", nil)
	w := httptest.NewRecorder()

	// TODO: wire to actual handler
	if w.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", w.Code)
	}
}
''',
            ".gitignore": "bin/\n*.exe\n*.log\n.env\n",
            "README.md": "# {{name}}\n\nGo API generated by apolo-dynamic-flow v2.7.0\n\n## Run\n\n```bash\ngo run main.go\n```\n",
        }
    },
    "python-cli": {
        "description": "Python CLI with Click, pytest, black, mypy",
        "languages": ["python"],
        "files": {
            "main.py": '''#!/usr/bin/env python3
"""{{name}} - CLI tool generated by apolo-dynamic-flow."""

import click


@click.command()
@click.option("--name", default="World", help="Name to greet")
def main(name: str):
    """Greet someone."""
    click.echo(f"Hello, {name}!")


if __name__ == "__main__":
    main()
''',
            "requirements.txt": "click>=8.0\npytest>=7.0\nblack>=23.0\nmypy>=1.0\n",
            "test_main.py": '''import pytest
from click.testing import CliRunner
from main import main


def test_main():
    runner = CliRunner()
    result = runner.invoke(main, ["--name", "Test"])
    assert result.exit_code == 0
    assert "Hello, Test" in result.output
''',
            ".gitignore": "__pycache__/\n*.pyc\n.venv/\n*.egg-info/\n.env\n",
            "README.md": "# {{name}}\n\nPython CLI generated by apolo-dynamic-flow v2.7.0\n\n## Install\n\n```bash\npip install -r requirements.txt\n```\n\n## Run\n\n```bash\npython main.py --name World\n```\n",
        }
    },
    "react-native": {
        "description": "React Native mobile app with TypeScript, Jest, Detox",
        "languages": ["typescript", "javascript"],
        "files": {
            "package.json": '''{
  "name": "{{name}}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "ios": "react-native run-ios",
    "android": "react-native run-android"
  },
  "dependencies": {
    "react": "^18.0.0",
    "react-native": "^0.73.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "typescript": "^5.5.0",
    "jest": "^29.0.0"
  }
}
''',
            "App.tsx": '''import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>{{name}}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, justifyContent: 'center', alignItems: 'center' },
});
''',
            ".gitignore": "node_modules/\n*.log\n.env\nios/Pods/\nandroid/.gradle/\n",
            "README.md": "# {{name}}\n\nReact Native app generated by apolo-dynamic-flow v2.7.0\n\n## Run\n\n```bash\nnpm install\nnpm run ios  # or android\n```\n",
        }
    },
    "rust-cli": {
        "description": "Rust CLI with clap, tokio, criterion benchmarks",
        "languages": ["rust"],
        "files": {
            "src/main.rs": '''use clap::Parser;

/// {{name}} - CLI tool generated by apolo-dynamic-flow
#[derive(Parser, Debug)]
#[command(version, about)]
struct Args {
    /// Name to greet
    #[arg(short, long, default_value = "World")]
    name: String,
}

fn main() {
    let args = Args::parse();
    println!("Hello, {}!", args.name);
}
''',
            "Cargo.toml": '''[package]
name = "{{name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
''',
            ".gitignore": "target/\n*.log\n.env\n",
            "README.md": "# {{name}}\n\nRust CLI generated by apolo-dynamic-flow v2.7.0\n\n## Build\n\n```bash\ncargo build --release\n```\n\n## Run\n\n```bash\ncargo run -- --name World\n```\n",
        }
    },
    "java-spring": {
        "description": "Java Spring Boot REST API with JUnit, Maven",
        "languages": ["java"],
        "files": {
            "pom.xml": '''<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>{{name}}</artifactId>
  <version>0.1.0</version>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.2.0</version>
  </parent>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
''',
            "src/main/java/com/example/Application.java": '''package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.*;

@SpringBootApplication
@RestController
public class Application {

    @GetMapping("/health")
    public String health() {
        return "{\\"status\\":\\"ok\\"}";
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
''',
            ".gitignore": "target/\n*.class\n*.log\n.env\n",
            "README.md": "# {{name}}\n\nJava Spring Boot API generated by apolo-dynamic-flow v2.7.0\n\n## Run\n\n```bash\nmvn spring-boot:run\n```\n",
        }
    },
    "php-laravel": {
        "description": "PHP Laravel API with PHPUnit",
        "languages": ["php"],
        "files": {
            "composer.json": '''{
  "name": "example/{{name}}",
  "type": "project",
  "require": {
    "php": "^8.2",
    "laravel/framework": "^11.0"
  },
  "require-dev": {
    "phpunit/phpunit": "^11.0"
  }
}
''',
            "public/index.php": '''<?php
require __DIR__.'/../vendor/autoload.php';
$app = require_once __DIR__.'/../bootstrap/app.php';
$app->run();
''',
            ".gitignore": "vendor/\n*.log\n.env\n",
            "README.md": "# {{name}}\n\nPHP Laravel API generated by apolo-dynamic-flow v2.7.0\n\n## Install\n\n```bash\ncomposer install\n```\n",
        }
    },
    "cpp-cmake": {
        "description": "C++ project with CMake, GoogleTest",
        "languages": ["cpp"],
        "files": {
            "CMakeLists.txt": '''cmake_minimum_required(VERSION 3.20)
project({{name}})

set(CMAKE_CXX_STANDARD 20)

add_executable({{name}} src/main.cpp)

# GoogleTest
enable_testing()
find_package(GTest)
if(GTest_FOUND)
    add_subdirectory(tests)
endif()
''',
            "src/main.cpp": '''#include <iostream>

int main() {
    std::cout << "Hello from {{name}}!" << std::endl;
    return 0;
}
''',
            ".gitignore": "build/\n*.o\n*.exe\n*.log\n",
            "README.md": "# {{name}}\n\nC++ project generated by apolo-dynamic-flow v2.7.0\n\n## Build\n\n```bash\nmkdir build && cd build\ncmake ..\nmake\n```\n",
        }
    },
}


def list_templates() -> str:
    """Lista todas las plantillas disponibles."""
    result = "Available templates:\n\n"
    for name, tmpl in TEMPLATES.items():
        result += f"  {name:<15} - {tmpl['description']}\n"
    return result


def create_project(template_name: str, output_dir: Path, project_name: str = "my-project") -> Dict:
    """Crea un proyecto desde una plantilla."""
    if template_name not in TEMPLATES:
        return {"success": False, "error": f"Template '{template_name}' not found. Use --list to see available templates."}

    template = TEMPLATES[template_name]
    output_dir.mkdir(parents=True, exist_ok=True)

    files_created = 0
    for rel_path, content in template["files"].items():
        # Substitute {{name}} with project_name
        content = content.replace("{{name}}", project_name)
        file_path = output_dir / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")
        files_created += 1

    return {
        "success": True,
        "template": template_name,
        "project_name": project_name,
        "output": str(output_dir),
        "files_created": files_created,
        "languages": template["languages"],
    }


def main() -> int:
    args = parse_args(sys.argv[1:])
    template = args.get("template", "")
    output = args.get("output", ".")
    project_name = args.get("name", "my-project")
    list_only = args.get("list", "") == "true"

    if list_only or not template:
        print(list_templates())
        return 0

    result = create_project(template, Path(output), project_name)
    print(json.dumps(result, indent=2))
    return 0 if result.get("success") else 1


if __name__ == "__main__":
    sys.exit(main())
